changes:
  base_url: "https://bspc.bstu.by"
  base_link: "/ru/uchashchimsya/zamena-zanyatij"
users:
  main_admin: 1827596987
bells:
  working_day:
    name: "Рабочий день"
    time:
      - - - "8:00"
          - "8:45"
        - - "8:55"
          - "9:40"
      - - - "9:50"
          - "10:35"
        - - "10:45"
          - "11:30"
      - - - "11:50"
          - "12:35"
        - - "12:45"
          - "13:30"
      - - - "14:25"
          - "15:10"
        - - "15:20"
          - "16:05"
      - - - "16:25"
          - "17:10"
        - - "17:20"
          - "18:05"
      - - - "18:15"
          - "19:00"
        - - "19:10"
          - "19:55"
  weekend_day:
    name: "Выходной день"
    time:
      - - - "8:00"
          - "8:45"
        - - "8:55"
          - "9:40"
      - - - "9:50"
          - "10:35"
        - - "10:45"
          - "11:30"
      - - - "11:40"
          - "12:25"
        - - "12:35"
          - "13:20"
      - - - "13:35"
          - "14:20"
        - - "14:30"
          - "15:15"
      - - - "15:25"
          - "16:10"
        - - "16:20"
          - "17:05"
      - - - "17:15"
          - "18:00"
        - - "18:10"
          - "18:55"
  shortened_day:
    name: "Сокращённый день"
    time:
      - - - "8:00"
          - "9:00"
      - - - "9:10"
          - "10:10"
      - - - "10:20"
          - "11:20"
      - - - "11:30"
          - "12:30"
      - - - "12:40"
          - "13:40"
      - - - "13:50"
          - "14:50"